### ISSUE TITLE
installation on Windows

### ISSUE THREAD

**Issue by BindingOx** [hanweg/mcp-discord#1]
Hi, on windows 10 and 11 I kept getting the error:

```plaintext
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 112, in _get_module_details
  File "D:\Development\mcp-discord\src\discord_mcp\__init__.py", line 3, in <module>
    from . import server
  File "D:\Development\mcp-discord\src\discord_mcp\server.py", line 8, in <module>
    import discord
  File "D:\Development\mcp-discord\.venv\Lib\site-packages\discord\__init__.py", line 23, in <module>
    from .client import *
  File "D:\Development\mcp-discord\.venv\Lib\site-packages\discord\client.py", line 51, in <module>
    from .sku import SKU, Entitlement
  File "D:\Development\mcp-discord\.venv\Lib\site-packages\discord\sku.py", line 31, in <module>
    from .app_commands import MissingApplicationID
  File "D:\Development\mcp-discord\.venv\Lib\site-packages\discord\app_commands\__init__.py", line 12, in <module>
    from .commands import *
  File "D:\Development\mcp-discord\.venv\Lib\site-packages\discord\app_commands\commands.py", line 53, in <module>
    from .models import Choice
  File "D:\Development\mcp-discord\.venv\Lib\site-packages\discord\app_commands\models.py", line 44, in <module>
    from ..member import Member
  File "D:\Development\mcp-discord\.venv\Lib\site-packages\discord\member.py", line 33, in <module>
    import discord.abc
  File "D:\Development\mcp-discord\.venv\Lib\site-packages\discord\abc.py", line 59, in <module>
    from .voice_client import VoiceClient, VoiceProtocol
  File "D:\Development\mcp-discord\.venv\Lib\site-packages\discord\voice_client.py", line 35, in <module>
    from .player import AudioPlayer, AudioSource
  File "D:\Development\mcp-discord\.venv\Lib\site-packages\discord\player.py", line 29, in <module>
    import audioop
ModuleNotFoundError: No module named 'audioop'
```

but fixed it with 

```shell
uv pip install audioop-lts
```

and might have to run again 

```shell
uv pip uninstall discord.py -y && uv pip install discord.py
```

**Comment by hanweg** [comment]
Thank you, audioop was removed in Python 3.13.  I will add that to the readme and try to get it into the install here shortly.


https://docs.python.org/3/library/audioop.html
